name: Check links
on: pull_request
jobs:
  check-links:
    runs-on: ubuntu-latest
    env:
      URL: https://deploy-preview-${{github.event.number}}--kuma.netlify.app
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-go@v3
      - run: |
          go install github.com/raviqqe/muffet/v2@v2.4.9
      - name: Wait for Pages changed to be neutral
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: waitForCheck
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Pages changed - kuma"
          timeoutSeconds: 1200
      - name: Wait for Netlify site to be ready
        if: steps.waitForCheck.outputs.conclusion == 'neutral'
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: waitForNetlify
        with:
          site_name: "kuma"
          max_timeout: 1200
      - name: link checker
        run: |
          `go env GOPATH`/bin/muffet ${URL} --max-connections-per-host=16 --exclude=twitter.com --exclude 127.0.0.1 --exclude 'https://github.com/spiffe/spiffe/blob/main/standards/X509-SVID.md.*' --rate-limit 100 --timeout 30 -v
